feat: Subscription Service for Auto-Swap
BlockheaderWeb3-Community/autoswappr-backend pull request #8
Opened 2024-11-27 21:04 UTC by Gerson2102

## Issue:
Solves #2 

## Changes
Adding the subscription file handling all the logic related to the requirements.
Adding new types
Adding new route

## Notes
I tested locally and is working. But I'm not 100% sure if this is what you guys want. Is my first time doing something like this.

2024-11-28 11:18 UTC, Abeeujah commented
Hi @Gerson2102 Great job so far, Could you add tests, and also run `cargo fmt` before you push, this should fix your CI build issue.

2024-11-28 23:37 UTC, Gerson2102 commented
AIght! @Abeeujah currently working on the tests.

2024-11-29 13:25 UTC, Abeeujah commented
Hi @Gerson2102 can you please fix CI issue?

2024-11-29 15:13 UTC, Gerson2102 commented
@Abeeujah can you run the the CI again to see what happens now please?

2024-11-29 18:57 UTC, sprtd commented
@Gerson2102 Kindly run `cargo fmt -- --check` locally; then fix the fmt error

2024-11-29 19:12 UTC, Abeeujah requested changes

2024-11-29 19:12 UTC, Abeeujah commented on tests/api/subscription.rs
> +
Hi, this test is failing due to you're passing an asynchronous operation into a synchronous operation, the order they complete is up to the workers that run the asynchronous operation, what I think you should test for is the `from_token` is stored correctly with the `percentage`
```rust
for (token, percentage) in payload.from_token.iter().zip(payload.percentage.iter()) {
        sqlx::query!(
            r#"
            INSERT INTO swap_subscription_from_token 
            (wallet_address, from_token, percentage)
            VALUES ($1, $2, $3)
            "#,
            payload.wallet_address,
            token,
            percentage,
        )
        .execute(&mut *tx)
        .await
        .map_err(|_| StatusCode::INTERNAL_SERVER_ERROR)?;
    }
```
so for a retrieved record
```rust
sqlx::query!(
        r#"
        SELECT wallet_address, from_token, percentage 
        FROM swap_subscription_from_token
        WHERE wallet_address = $1 AND from_token = $2
        "#,
        wallet_address,
        from_token,
    )
    ```
    assert that the from_token percent is set properly.

2024-11-29 19:25 UTC, Gerson2102 commented on src/http/subscription.rs
> +
Got it

2024-11-29 19:38 UTC, Gerson2102 commented
I dont know how to make the tests working from the first time that we run `cargo test`. @Abeeujah

2024-11-29 21:20 UTC, merged