Feat: added activity_log_retrieval
BlockheaderWeb3-Community/autoswappr-backend pull request #9
Opened 2024-11-28 14:09 UTC by RichoKD

2024-11-29 13:22 UTC, Abeeujah commented
Hi @RichoKD could you please fix failing CI

2024-11-29 14:35 UTC, RichoKD commented
> Hi @RichoKD could you please fix failing CI

I've done it

2024-11-29 19:35 UTC, Abeeujah requested changes

2024-11-29 19:35 UTC, Abeeujah commented on src/api_error.rs
Hi, can you revert the change you made here?

2024-11-29 19:35 UTC, Abeeujah commented on tests/api/activity_log_retrieval.rs
> +}
Also could you include test cases that check for errors and edge cases eg empty transactions log

2024-11-29 19:50 UTC, RichoKD commented on src/api_error.rs
Ok

2024-11-29 20:03 UTC, Abeeujah commented on tests/api/activity_log_retrieval.rs
> +}
![_home_abee_Desktop_OdHack_autoswappr-backend_tarpaulin-report html](https://github.com/user-attachments/assets/88c2484d-ac75-4c75-b6b6-bf0b58a51cb8)
Here's the result of your current test coverage...

2024-11-30 11:27 UTC, RichoKD commented on tests/api/activity_log_retrieval.rs
> +}
I've updated it

2024-11-30 16:56 UTC, RichoKD commented on tests/api/activity_log_retrieval.rs
> +}
Done

2024-12-01 12:45 UTC, merged